### ISSUE TITLE
ValueError: Namespace WebKit2 not available

### ISSUE THREAD

**Issue by mphaines86** [utknoxville/openconnect-pulse-gui#1]
Using Ubuntu 18.04, I got the following error despite following the instructions in the readme:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/michael/tmp/openconnect-pulse-gui/openconnect_pulse_gui/__init__.py", line 1, in <module>
    from .openconnect_pulse_gui import main
  File "/home/michael/tmp/openconnect-pulse-gui/openconnect_pulse_gui/openconnect_pulse_gui.py", line 25, in <module>
    gi.require_version("WebKit2", "4.0")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit2 not available
```

It appears installing gir1.2-webkit2-4.0 fixes the issue however. Just want to bring this to your attention in case others run into the issue.

**Comment by kbirkeland** [comment]
Thanks for the issue report!  I have updated the instructions to reflect the package correction.
