### ISSUE TITLE
Error: 'Cookie' object has no attribute 'name'

### ISSUE THREAD

**Issue by lrfinotti** [utknoxville/openconnect-pulse-gui#21]
I am trying to use this as an alternative to Pulse VPN, as its app is not compatible with Debian Sid/Unstable, as it requires libwebkit2gtk-4.0-37, while in Debian Sid we have only libwebkit2gtk-4.1-0.

First, I needed to change line 25 of `openconnect_pulse_gui.py` from
```python
gi.require_version("WebKit2", "4.0")
```
to
```python
gi.require_version("WebKit2", "4.1")
```
in the current version (similar to the problem with the official Pulse application), which seems to work, as I do get a Duo window and all.

But I do get the following errors:

```
$ ./openconnect_pulse_gui.py access.utk.edu
WARNING:pulsegui:Running as non-root user. Will not run openconnect, only print the command
Traceback (most recent call last):
  File "/home/finotti/src/openconnect-pulse-gui/openconnect_pulse_gui/./openconnect_pulse_gui.py", line 181, in _check_for_authcookie
    if cookie.name == self._session_cookie_name:
       ^^^^^^^^^^^
AttributeError: 'Cookie' object has no attribute 'name'
Traceback (most recent call last):
  File "/home/finotti/src/openconnect-pulse-gui/openconnect_pulse_gui/./openconnect_pulse_gui.py", line 181, in _check_for_authcookie
    if cookie.name == self._session_cookie_name:
```
This is repeated many times.  I can login, using my UTID and Duo verification, but what I get is the window below:

![Screenshot_20240709_082527](https://github.com/utknoxville/openconnect-pulse-gui/assets/22774569/e5de5c27-f523-4846-9940-0182fb6510f7)

I get no command to use with openconnect.  

Any ideas?

**Comment by bredelings** [comment]
It looks like the cookie fields have to be accessed via getters in webkit2 version 4.1.  So, I replaced `cookie.name` with `cookie.get_name()`.
[webkit2-4.1.patch.txt](https://github.com/user-attachments/files/16354914/webkit2-4.1.patch.txt)

**Comment by lrfinotti** [comment]
Thanks, that indeed fixed the error!

But I get the same screen as above and no command to use.  Is this script still working?

In the terminal I get

```
$ ./openconnect_pulse_gui.py access.utk.edu
WARNING:pulsegui:Running as non-root user. Will not run openconnect, only print the command
ERROR:pulsegui:Login window closed by user
```

Is there something else I need to do when I get to the window?  I see no option that seems relevant.

**Comment by bredelings** [comment]
For me, it fixed the issue.  Instead of getting to the settings screen at before, I got a DSID cookie, and then the script quit with a command.  If you don't get a DSID cookie, then you won't get a command.

Maybe add something like `print(f"{cookie.get_name()} = {cookie.get_value()})` in side the `for cookie in cookies` loop in `_check_for_authcookie`?  If there is no cookie called `DSID`, then its possible that you need to use the `--session-cookie-name` argument to something else.

**Comment by lrfinotti** [comment]
I am sorry for the false report...  I had a typo.  It does work!  This is a huge help!  Thank you very much for your help!
